 int _putchar(char c);
void print_numbers(void);
void print_alphabet_x10(void);
int _isupper(int c);
int _isdigit(int c);
int print_sign(int n);
int _abs(int);
int print_last_digit(int);
void jack_bauer(void);
void times_table(void);
int mul(int a, int b);
void print_to_98(int n);
